### ISSUE TITLE
Como instalar no Discord?

### ISSUE THREAD

**Issue by joaomantovani** [tiago154/discord-bot-guilda-nodejs#1]
**Is your feature request related to a problem? Please describe.**
Bot

**Describe the solution you'd like**
Não manjo muito no Discord, como faria para instalar o bot em algum server no discord?

**Additional context**
Talvez colocar no readme.md dps

**Comment by tiago154** [comment]
Opa @joaomantovani a ideia é que o próprio desenvolvedor crie seu bot no painel de [aplicações discord](https://discord.com/developers/applications). Lá será possível criar seu app + bot. Depois que for criado, na aba de oauth2 é possível gerar a URL que você pode repassar para adicionar seu bot em qualquer servidor, esse trecho está descrito no [README](https://github.com/tiago154/discord-bot-guilda-nodejs/blob/master/README.md#instalando).

Você acha que seria legal realizar essa explicação no Readme?

**Comment by joaomantovani** [comment]
Eu acho bem interessante, como não pude participar da guilda, não sabia dessa explicação que provavelmente foi explicada la!
